# Generated by Django 4.2.5 on 2023-09-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catogory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catogory_name', models.CharField(max_length=100, unique=True)),
                ('Catogory_description', models.CharField(blank=True, max_length=100)),
                ('Catogory_image', models.ImageField(upload_to='static/img')),
            ],
        ),
    ]
