# Generated by Django 4.2.5 on 2023-09-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
