# Generated by Django 4.2.1 on 2023-09-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
