# Generated by Django 4.2.5 on 2023-09-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0007_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
