# Generated by Django 4.2.5 on 2023-09-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0008_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
