# Generated by Django 4.2.5 on 2023-09-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0009_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_image',
        ),
    ]
