# Generated by Django 4.2.5 on 2023-09-22 02:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0010_remove_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/img'),
            preserve_default=False,
        ),
    ]
